//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY
    {
        public FACULTY()
        {
            this.BLOGs = new HashSet<BLOG>();
            this.READING_ROOM = new HashSet<READING_ROOM>();
            this.USERs = new HashSet<USER>();
        }
    
        public long FAC_ID { get; set; }
        public long UNI_ID { get; set; }
        public string FAC_NAME { get; set; }
        public string FAC_ABBR { get; set; }
        public string FAC_ADDR { get; set; }
        public string FAC_WEB { get; set; }
        public string FAC_EMAIL { get; set; }
        public string FAC_TEL { get; set; }
    
        public virtual ICollection<BLOG> BLOGs { get; set; }
        public virtual UNIVERSITY UNIVERSITY { get; set; }
        public virtual ICollection<READING_ROOM> READING_ROOM { get; set; }
        public virtual ICollection<USER> USERs { get; set; }
    }
}
