//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public POST()
        {
            this.REPORTs = new HashSet<REPORT>();
        }
    
        public long POST_ID { get; set; }
        public long USR_ID { get; set; }
        public long THREAD_ID { get; set; }
        public string POST_CON { get; set; }
        public Nullable<long> POST_LIKES { get; set; }
        public Nullable<long> POST_DISLIKES { get; set; }
        public System.DateTime POST_CRON { get; set; }
    
        public virtual THREAD THREAD { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<REPORT> REPORTs { get; set; }
    }
}
