//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReadingRoomsEntities : DbContext
    {
        public ReadingRoomsEntities()
            : base("name=ReadingRoomsEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BLOG> BLOGs { get; set; }
        public DbSet<FACULTY> FACULTies { get; set; }
        public DbSet<POST> POSTs { get; set; }
        public DbSet<READING_ROOM> READING_ROOM { get; set; }
        public DbSet<REPORT> REPORTs { get; set; }
        public DbSet<RESERVATION> RESERVATIONs { get; set; }
        public DbSet<SEAT> SEATs { get; set; }
        public DbSet<THREAD> THREADs { get; set; }
        public DbSet<UNIVERSITY> UNIVERSITies { get; set; }
        public DbSet<USER> USERs { get; set; }
    }
}
