//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class READING_ROOM
    {
        public READING_ROOM()
        {
            this.SEATs = new HashSet<SEAT>();
        }
    
        public long RROOM_ID { get; set; }
        public Nullable<long> FAC_ID { get; set; }
        public Nullable<long> UNI_ID { get; set; }
        public string RROOM_NAME { get; set; }
        public Nullable<decimal> RROOM_LON { get; set; }
        public Nullable<decimal> RROOM_LAT { get; set; }
        public int RROOM_DIM { get; set; }
        public System.DateTime RROOM_WTF { get; set; }
        public System.DateTime RROOM_WTT { get; set; }
        public bool RROOM_IDX { get; set; }
        public Nullable<System.DateTime> RROOM_IDXF { get; set; }
        public Nullable<System.DateTime> RROOM_IDXT { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
        public virtual UNIVERSITY UNIVERSITY { get; set; }
        public virtual ICollection<SEAT> SEATs { get; set; }
    }
}
