//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public long REPO_ID { get; set; }
        public Nullable<long> POST_ID { get; set; }
        public long USR_ID { get; set; }
        public Nullable<long> THREAD_ID { get; set; }
        public string REPO_REASON { get; set; }
        public System.DateTime REPO_CRON { get; set; }
        public Nullable<bool> REPO_ACCEPT { get; set; }
    
        public virtual POST POST { get; set; }
        public virtual THREAD THREAD { get; set; }
        public virtual USER USER { get; set; }
    }
}
