//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAT
    {
        public SEAT()
        {
            this.RESERVATIONs = new HashSet<RESERVATION>();
        }
    
        public long SEAT_ID { get; set; }
        public long RROOM_ID { get; set; }
        public int SEAT_POSITION { get; set; }
        public string SEAT_LABEL { get; set; }
    
        public virtual READING_ROOM READING_ROOM { get; set; }
        public virtual ICollection<RESERVATION> RESERVATIONs { get; set; }
    }
}
