//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THREAD
    {
        public THREAD()
        {
            this.POSTs = new HashSet<POST>();
            this.REPORTs = new HashSet<REPORT>();
        }
    
        public long THREAD_ID { get; set; }
        public long BLOG_ID { get; set; }
        public long USR_ID { get; set; }
        public string THREAD_H { get; set; }
        public string THREAD_CON { get; set; }
        public System.DateTime THREAD_CRON { get; set; }
    
        public virtual BLOG BLOG { get; set; }
        public virtual ICollection<POST> POSTs { get; set; }
        public virtual ICollection<REPORT> REPORTs { get; set; }
        public virtual USER USER { get; set; }
    }
}
