//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIVERSITY
    {
        public UNIVERSITY()
        {
            this.FACULTies = new HashSet<FACULTY>();
            this.READING_ROOM = new HashSet<READING_ROOM>();
        }
    
        public long UNI_ID { get; set; }
        public string UNI_NAME { get; set; }
        public string UNI_CITY { get; set; }
    
        public virtual ICollection<FACULTY> FACULTies { get; set; }
        public virtual ICollection<READING_ROOM> READING_ROOM { get; set; }
    }
}
