//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.POSTs = new HashSet<POST>();
            this.REPORTs = new HashSet<REPORT>();
            this.RESERVATIONs = new HashSet<RESERVATION>();
            this.THREADs = new HashSet<THREAD>();
        }
    
        public long USR_ID { get; set; }
        public Nullable<long> FAC_ID { get; set; }
        public string USR_USERNAME { get; set; }
        public string USR_PASS { get; set; }
        public string USR_EMAIL { get; set; }
        public string USR_NAME { get; set; }
        public string USR_LNAME { get; set; }
        public string USR_IDX { get; set; }
        public string USR_ROLE { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
        public virtual ICollection<POST> POSTs { get; set; }
        public virtual ICollection<REPORT> REPORTs { get; set; }
        public virtual ICollection<RESERVATION> RESERVATIONs { get; set; }
        public virtual ICollection<THREAD> THREADs { get; set; }
    }
}
